version: '3'

services:
  icebox:
    image: cryogenics/bbr-sdk-icebox:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: ["cryogenics"]
    volumes:
      - custom-settings:/home/cryogenist
      - .:/home/cryogenist/workspace:cached

volumes:
  custom-settings: