---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: backup-and-restore-sdk-release

params:
  GITHUB_TOKEN:
  URL:
  METHOD: MERGE
  DELETE: FALSE

run:
  path: backup-and-restore-sdk-release/ci/tasks/merge-pr/task.sh