---
platform: linux

image_resource:
  type: registry-image
  source: {repository: pcfplatformrecovery/backup-and-restore}

inputs:
- name: task-repo
- name: bump-repo

params:
  DESCRIPTOR_PATH:
  # Mandatory params without defaults
  GH_TOKEN:
  PR_BASE:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:

  # Optional params without defaults
  PR_LABELS:

  # Optional params with sane defaults for cryogenics
  # Default values are set in the script itself
  GH_USER:
  COMMIT_USERNAME:
  COMMIT_USEREMAIL:
  COMMIT_MESSAGE:
  PR_TITLE:
  PR_MESSAGE:

run:
  path: task-repo/ci/tasks/bump-generic/task.sh "bump-repo/${DESCRIPTOR_PATH}"